#!/usr/bin/env bun

const dir = new URL("..", import.meta.url).pathname;
process.chdir(dir);

import { $ } from "bun";
import path from "path";
import { color } from "../src/tokens/color.ts";
import { font } from "../src/tokens/font.ts";
import { motion } from "../src/tokens/motion.ts";
import { radius } from "../src/tokens/radius.ts";
import { shadow } from "../src/tokens/shadow.ts";
import { space } from "../src/tokens/space.ts";
import { typography } from "../src/tokens/typography.ts";

const HEADER = `/* Generated by scripts/build-tokens.ts. Do not edit by hand.
   Source of truth: src/tokens/*.ts */\n\n`;

const colorVars: string[] = [];
for (const [name, value] of Object.entries(color.paper)) {
  colorVars.push(`  --paper-${name}: ${value};`);
}
colorVars.push("");
for (const [name, value] of Object.entries(color.slate)) {
  colorVars.push(`  --slate-${name}: ${value};`);
}
colorVars.push("");
for (const [name, value] of Object.entries(color.wine)) {
  colorVars.push(`  --wine-${name}: ${value};`);
}
colorVars.push("");
for (const [name, value] of Object.entries(color.sepia)) {
  colorVars.push(`  --sepia-${name}: ${value};`);
}
colorVars.push("");
for (const [name, value] of Object.entries(color.night)) {
  colorVars.push(`  --night-${name}: ${value};`);
}
colorVars.push("");
for (const [name, value] of Object.entries(color.highlight)) {
  colorVars.push(`  --hl-${name}: ${value};`);
}
colorVars.push("");
for (const [name, value] of Object.entries(color.status)) {
  colorVars.push(`  --${name}: ${value};`);
}

const fontVars: string[] = [
  `  --font-display: ${font.family.display};`,
  `  --font-reading: ${font.family.reading};`,
  `  --font-ui: ${font.family.ui};`,
  `  --font-mono: ${font.family.mono};`,
];

const spaceVars: string[] = [];
for (const [name, value] of Object.entries(space)) {
  spaceVars.push(`  --space-${name}: ${value === 0 ? "0" : `${value}px`};`);
}

const radiusVars: string[] = [];
for (const [name, value] of Object.entries(radius)) {
  radiusVars.push(`  --r-${name}: ${value === 0 ? "0" : `${value}px`};`);
}

const shadowVars: string[] = [];
for (const [name, value] of Object.entries(shadow)) {
  shadowVars.push(`  --sh-${name}: ${value};`);
}

const motionVars: string[] = [];
for (const [name, value] of Object.entries(motion)) {
  motionVars.push(`  --m-${name}: ${value};`);
}

const tokensCss = `${HEADER}:root {
  /* paper neutrals */
${colorVars.filter((l) => l.includes("--paper-")).join("\n")}

  /* slate (cool UI) */
${colorVars.filter((l) => l.includes("--slate-")).join("\n")}

  /* wine accent */
${colorVars.filter((l) => l.includes("--wine-")).join("\n")}

  /* sepia */
${colorVars.filter((l) => l.includes("--sepia-")).join("\n")}

  /* night */
${colorVars.filter((l) => l.includes("--night-")).join("\n")}

  /* highlights */
${colorVars.filter((l) => l.includes("--hl-")).join("\n")}

  /* status */
${colorVars
  .filter(
    (l) =>
      l.includes("--success") ||
      l.includes("--warning") ||
      l.includes("--error") ||
      l.includes("--info"),
  )
  .join("\n")}

  /* fonts */
${fontVars.join("\n")}

  /* spacing (4pt grid) */
${spaceVars.join("\n")}

  /* radii */
${radiusVars.join("\n")}

  /* shadows */
${shadowVars.join("\n")}

  /* motion */
${motionVars.join("\n")}
}
`;

function classSuffix(key: string): string {
  return key.replace(/([A-Z]+)/g, "-$1").toLowerCase();
}

function fontFamilyToken(family: string): string {
  if (family === font.family.display) return "var(--font-display)";
  if (family === font.family.reading) return "var(--font-reading)";
  if (family === font.family.ui) return "var(--font-ui)";
  if (family === font.family.mono) return "var(--font-mono)";
  return family;
}

const presetBlocks: string[] = [];
for (const [key, preset] of Object.entries(typography)) {
  const props: string[] = [
    `  font-family: ${fontFamilyToken(preset.fontFamily)};`,
    `  font-weight: ${preset.fontWeight};`,
    `  font-size: ${preset.fontSize}px;`,
    `  line-height: ${preset.lineHeight};`,
  ];
  if ("letterSpacing" in preset && preset.letterSpacing !== undefined) {
    props.push(`  letter-spacing: ${preset.letterSpacing}em;`);
  }
  if ("textTransform" in preset && preset.textTransform) {
    props.push(`  text-transform: ${preset.textTransform};`);
  }
  if ("textAlign" in preset && preset.textAlign) {
    props.push(`  text-align: ${preset.textAlign};`);
  }
  if ("fontVariationSettings" in preset && preset.fontVariationSettings) {
    props.push(`  font-variation-settings: ${preset.fontVariationSettings};`);
  }
  presetBlocks.push(`.t-${classSuffix(key)} {\n${props.join("\n")}\n}`);
}

const typographyCss = `${HEADER}${presetBlocks.join("\n\n")}\n`;

const indexCss = `${HEADER}@import "./tokens.css";
@import "./reset.css";
@import "./theme.css";
@import "./typography.css";
@import "./primitives.css";
@import "./reader.css";
`;

const stylesDir = path.join(dir, "src", "styles");
await Bun.write(path.join(stylesDir, "tokens.css"), tokensCss);
await Bun.write(path.join(stylesDir, "typography.css"), typographyCss);
await Bun.write(path.join(stylesDir, "index.css"), indexCss);

console.log("Wrote src/styles/{tokens,typography,index}.css");

await $`bun run lint:fix`;
await $`bun run format:fix`;
await $`bun run ts-check`;
