import { StyleSheet } from "react-native";
import { color, font, radius } from "@bainder/ui";

export const authStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: color.paper[50],
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 24,
  },
  back: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.pill,
  },
  intro: {
    marginTop: 24,
    gap: 28,
  },
  monogram: {
    width: 56,
    height: 56,
    borderRadius: 16,
  },
  monogramText: {
    fontSize: 32,
    lineHeight: 32,
  },
  title: {
    fontFamily: font.nativeFamily.display,
    fontSize: 38,
    fontWeight: "400",
    lineHeight: 39,
    letterSpacing: 0,
    color: color.paper[900],
  },
  lead: {
    marginTop: 12,
    maxWidth: 300,
    fontFamily: font.nativeFamily.ui,
    fontSize: 15,
    lineHeight: 22,
    color: color.paper[600],
  },
  form: {
    marginTop: 32,
    gap: 14,
  },
  socialButton: {
    height: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    borderRadius: radius.pill,
  },
  socialButtonGoogle: {
    backgroundColor: color.paper[50],
    borderWidth: 1,
    borderColor: color.paper[300],
  },
  socialButtonApple: {
    backgroundColor: color.paper[900],
  },
  pressed: {
    transform: [{ scale: 0.98 }],
  },
  socialLabel: {
    fontFamily: font.nativeFamily.ui,
    fontSize: 16,
    fontWeight: "500",
    color: color.paper[900],
  },
  socialLabelApple: {
    color: color.paper[50],
  },
  socialMark: {
    width: 18,
    textAlign: "center",
    fontFamily: font.nativeFamily.ui,
    fontSize: 17,
    fontWeight: "700",
    lineHeight: 20,
  },
  socialMarkGoogle: {
    color: "#4285F4",
  },
  socialMarkApple: {
    color: color.paper[50],
  },
  divider: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  line: {
    flex: 1,
    height: 1,
    backgroundColor: color.paper[200],
  },
  dividerLabel: {
    fontFamily: font.nativeFamily.ui,
    fontSize: 11,
    fontWeight: "500",
    letterSpacing: 0.44,
    color: color.paper[500],
  },
  label: {
    marginBottom: 8,
    fontFamily: font.nativeFamily.ui,
    fontSize: 11,
    fontWeight: "500",
    letterSpacing: 0.44,
    color: color.paper[600],
  },
  inputWrap: {
    width: "100%",
  },
  input: {
    backgroundColor: color.paper[50],
    borderColor: color.paper[300],
  },
  footer: {
    marginTop: "auto",
    alignItems: "center",
    paddingTop: 32,
  },
  switchText: {
    fontFamily: font.nativeFamily.ui,
    fontSize: 13,
    lineHeight: 18,
    color: color.paper[500],
  },
  switchLink: {
    color: color.paper[900],
    fontWeight: "500",
    textDecorationLine: "underline",
  },
  legal: {
    marginTop: 12,
    maxWidth: 300,
    textAlign: "center",
    fontFamily: font.nativeFamily.ui,
    fontSize: 13,
    lineHeight: 18,
    color: color.paper[500],
  },
  error: {
    fontFamily: font.nativeFamily.ui,
    fontSize: 13,
    lineHeight: 18,
    color: color.status.error,
  },
  otpIntro: {
    marginTop: 32,
  },
  eyebrow: {
    marginBottom: 10,
    fontFamily: font.nativeFamily.ui,
    fontSize: 11,
    fontWeight: "500",
    letterSpacing: 0.44,
    color: color.paper[500],
  },
  otpTitle: {
    fontFamily: font.nativeFamily.display,
    fontSize: 36,
    fontWeight: "400",
    lineHeight: 38,
    letterSpacing: 0,
    color: color.paper[900],
  },
  otpLead: {
    marginTop: 14,
    maxWidth: 300,
    fontFamily: font.nativeFamily.ui,
    fontSize: 15,
    lineHeight: 22,
    color: color.paper[600],
  },
  emailStrong: {
    color: color.paper[900],
    fontWeight: "500",
  },
  otpRow: {
    position: "relative",
    marginTop: 36,
    flexDirection: "row",
    gap: 8,
  },
  otpInput: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
    opacity: 0,
  },
  otpBox: {
    flex: 1,
    aspectRatio: 0.85,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: color.paper[100],
    borderWidth: 1,
    borderColor: "transparent",
  },
  otpBoxActive: {
    borderColor: color.paper[900],
  },
  otpDigit: {
    fontFamily: font.nativeFamily.display,
    fontSize: 28,
    fontWeight: "500",
    lineHeight: 32,
    color: color.paper[900],
  },
  otpCaret: {
    width: 1,
    height: 24,
    backgroundColor: color.paper[900],
  },
  otpActions: {
    marginTop: 24,
    gap: 12,
  },
  tip: {
    marginTop: "auto",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 14,
    backgroundColor: color.paper[100],
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  tipText: {
    flex: 1,
    fontFamily: font.nativeFamily.ui,
    fontSize: 13,
    lineHeight: 18,
    color: color.paper[700],
  },
});
