const { getDefaultConfig } = require("expo/metro-config");
const path = require("path");

const projectRoot = __dirname;
const workspaceRoot = path.resolve(projectRoot, "../..");

const config = getDefaultConfig(projectRoot);

config.watchFolders = [workspaceRoot];
config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, "node_modules"),
  path.resolve(workspaceRoot, "node_modules"),
];
config.resolver.unstable_enablePackageExports = true;

// Force a single copy of react and react-native across the workspace.
// Without this, Bun's isolated linker installs a per-package react-native
// inside @bainder/ui, producing two RN renderers and breaking hooks.
const SINGLETONS = ["react", "react-native"];
const originalResolveRequest = config.resolver.resolveRequest;

const resolveWith = (context, moduleName, platform) => {
  if (originalResolveRequest) return originalResolveRequest(context, moduleName, platform);
  return context.resolveRequest(context, moduleName, platform);
};

config.resolver.resolveRequest = (context, moduleName, platform) => {
  const isSingleton = SINGLETONS.some(
    (name) => moduleName === name || moduleName.startsWith(`${name}/`),
  );
  const ctx = isSingleton
    ? { ...context, originModulePath: path.join(projectRoot, "_singleton.js") }
    : context;

  // Relative .js imports inside TS-source workspace packages (e.g. @bainder/sdk
  // generated by openapi-ts) need to be remapped to the actual .ts/.tsx file.
  if (moduleName.endsWith(".js") && (moduleName.startsWith("./") || moduleName.startsWith("../"))) {
    const base = moduleName.slice(0, -3);
    for (const ext of [".ts", ".tsx"]) {
      try {
        return resolveWith(ctx, base + ext, platform);
      } catch {
        // try next
      }
    }
  }

  return resolveWith(ctx, moduleName, platform);
};

module.exports = config;
