import { StyleSheet } from "react-native";
import { color, font, radius } from "@bainder/ui";

export const dashboardStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: color.paper[50],
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 24,
  },
  nav: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  navActions: {
    flexDirection: "row",
    gap: 8,
  },
  iconButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.pill,
    backgroundColor: color.paper[100],
  },
  searchWrap: {
    marginTop: 14,
  },
  greeting: {
    paddingTop: 14,
    paddingBottom: 4,
  },
  eyebrow: {
    fontFamily: font.nativeFamily.ui,
    fontSize: 11,
    fontWeight: "500",
    letterSpacing: 0.44,
    color: color.paper[500],
  },
  title: {
    marginTop: 4,
    fontFamily: font.nativeFamily.display,
    fontSize: 30,
    fontWeight: "400",
    lineHeight: 32,
    letterSpacing: 0,
    color: color.paper[900],
  },
  error: {
    marginTop: 12,
    borderRadius: radius.md,
    backgroundColor: color.wine[50],
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontFamily: font.nativeFamily.ui,
    fontSize: 13,
    color: color.status.error,
  },
  loading: {
    marginTop: 18,
    gap: 12,
  },
  quickAdd: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: radius.pill,
    backgroundColor: color.paper[100],
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  quickAddText: {
    flex: 1,
    fontFamily: font.nativeFamily.ui,
    fontSize: 13,
    color: color.paper[500],
  },
  pressed: {
    transform: [{ scale: 0.99 }],
  },
  section: {
    marginTop: 20,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  sectionTitle: {
    fontFamily: font.nativeFamily.display,
    fontSize: 18,
    fontWeight: "500",
    lineHeight: 22,
    color: color.paper[900],
  },
  sectionMeta: {
    fontFamily: font.nativeFamily.ui,
    fontSize: 13,
    color: color.paper[500],
  },
  stack: {
    gap: 8,
  },
  documentRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 12,
  },
  documentBody: {
    flex: 1,
    minWidth: 0,
  },
  kindLabel: {
    marginBottom: 2,
    fontFamily: font.nativeFamily.ui,
    fontSize: 9,
    fontWeight: "500",
    letterSpacing: 0.36,
    color: color.paper[500],
  },
  documentTitle: {
    fontFamily: font.nativeFamily.ui,
    fontSize: 13,
    fontWeight: "500",
    lineHeight: 17,
    color: color.paper[900],
  },
  documentSub: {
    marginTop: 2,
    fontFamily: font.nativeFamily.ui,
    fontSize: 11,
    lineHeight: 15,
    color: color.paper[500],
  },
  progressTrack: {
    marginTop: 8,
    height: 3,
    overflow: "hidden",
    borderRadius: radius.pill,
    backgroundColor: color.paper[200],
  },
  progressFill: {
    height: "100%",
    borderRadius: radius.pill,
  },
  emptyCard: {
    padding: 18,
  },
  emptyCardText: {
    fontFamily: font.nativeFamily.ui,
    fontSize: 13,
    lineHeight: 18,
    color: color.paper[600],
  },
  recentGrid: {
    marginTop: 10,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
  },
  recentCard: {
    width: 104,
  },
  recentTextRow: {
    marginTop: 8,
    flexDirection: "row",
    alignItems: "flex-start",
  },
  recentText: {
    flex: 1,
    minWidth: 0,
  },
  recentTitle: {
    fontFamily: font.nativeFamily.ui,
    fontSize: 12,
    fontWeight: "500",
    lineHeight: 15,
    color: color.paper[900],
  },
  recentSub: {
    marginTop: 2,
    fontFamily: font.nativeFamily.ui,
    fontSize: 11,
    color: color.paper[500],
  },
  dropWrap: {
    marginTop: 16,
  },
  dropZone: {
    minHeight: 360,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: color.paper[300],
    borderRadius: 22,
    backgroundColor: color.paper[100],
    padding: 24,
  },
  faintCover: {
    position: "absolute",
    width: 58,
    height: 82,
    justifyContent: "flex-end",
    borderRadius: 4,
    backgroundColor: color.highlight.blue,
    opacity: 0.2,
    padding: 8,
  },
  faintCoverLeft: {
    left: 20,
    top: 32,
    transform: [{ rotate: "-9deg" }],
  },
  faintCoverRight: {
    right: 22,
    bottom: 42,
    transform: [{ rotate: "6deg" }],
  },
  faintCoverText: {
    fontFamily: font.nativeFamily.display,
    fontSize: 10,
    fontWeight: "500",
    lineHeight: 12,
    color: color.paper[900],
  },
  dropIcon: {
    zIndex: 1,
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.pill,
    backgroundColor: color.paper[50],
    shadowColor: color.paper[900],
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
  },
  dropTitle: {
    zIndex: 1,
    marginTop: 14,
    textAlign: "center",
    fontFamily: font.nativeFamily.display,
    fontSize: 18,
    fontWeight: "500",
    color: color.paper[900],
  },
  dropLead: {
    zIndex: 1,
    marginTop: 4,
    textAlign: "center",
    fontFamily: font.nativeFamily.ui,
    fontSize: 12,
    lineHeight: 17,
    color: color.paper[700],
  },
  linkImport: {
    zIndex: 1,
    marginTop: 14,
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: color.paper[300],
    borderRadius: radius.pill,
    backgroundColor: color.paper[50],
    padding: 4,
  },
  linkPlaceholder: {
    flex: 1,
    paddingLeft: 12,
    fontFamily: font.nativeFamily.ui,
    fontSize: 11,
    color: color.paper[500],
  },
  linkButton: {
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.pill,
    backgroundColor: color.paper[900],
    paddingHorizontal: 14,
  },
  linkButtonText: {
    fontFamily: font.nativeFamily.ui,
    fontSize: 11,
    fontWeight: "500",
    color: color.paper[50],
  },
  dropHints: {
    marginTop: 14,
    gap: 8,
  },
  importHint: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  importHintText: {
    fontFamily: font.nativeFamily.ui,
    fontSize: 12,
    color: color.paper[600],
  },
  filteredEmpty: {
    marginTop: 24,
    alignItems: "center",
    padding: 28,
  },
  filteredTitle: {
    marginTop: 12,
    fontFamily: font.nativeFamily.display,
    fontSize: 22,
    fontWeight: "500",
    color: color.paper[900],
  },
  filteredBody: {
    marginTop: 4,
    fontFamily: font.nativeFamily.ui,
    fontSize: 13,
    color: color.paper[600],
  },
  tabs: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    justifyContent: "space-around",
    borderTopWidth: 1,
    borderTopColor: color.paper[200],
    backgroundColor: color.paper[50],
    paddingTop: 12,
  },
  tabItem: {
    minWidth: 52,
    alignItems: "center",
    gap: 4,
  },
  primaryTab: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radius.pill,
    backgroundColor: color.paper[900],
  },
  tabLabel: {
    fontFamily: font.nativeFamily.ui,
    fontSize: 10,
    color: color.paper[500],
  },
  tabLabelActive: {
    color: color.paper[900],
    fontWeight: "600",
  },
  toastWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    alignItems: "center",
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(20,15,10,0.35)",
  },
  modalSheet: {
    gap: 12,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: color.paper[50],
    padding: 20,
    paddingBottom: 40,
  },
  modalHeader: {
    marginBottom: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalTitle: {
    fontFamily: font.nativeFamily.ui,
    fontSize: 17,
    fontWeight: "500",
    color: color.paper[900],
  },
  modalBody: {
    fontFamily: font.nativeFamily.ui,
    fontSize: 15,
    lineHeight: 22,
    color: color.paper[700],
  },
  modalStrong: {
    fontWeight: "600",
  },
  modalFooter: {
    marginTop: 12,
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
  },
});
