import { StyleSheet } from "react-native";
import { color, font, radius, type ThemeColors } from "@baindar/ui";

export const buildDashboardStyles = (palette: ThemeColors) =>
  StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: palette.bg,
    },
    scroll: {
      flex: 1,
    },
    content: {
      paddingHorizontal: 24,
    },
    nav: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    navActions: {
      flexDirection: "row",
      gap: 8,
    },
    iconButton: {
      width: 36,
      height: 36,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: radius.pill,
      backgroundColor: palette.surfaceRaised,
    },
    searchWrap: {
      marginTop: 14,
    },
    greeting: {
      paddingTop: 14,
      paddingBottom: 4,
    },
    eyebrow: {
      fontFamily: font.nativeFamily.ui,
      fontSize: 11,
      fontWeight: "500",
      letterSpacing: 0.44,
      color: palette.fgMuted,
    },
    title: {
      marginTop: 4,
      fontFamily: font.nativeFamily.display,
      fontSize: 30,
      fontWeight: "400",
      lineHeight: 32,
      letterSpacing: 0,
      color: palette.fg,
    },
    error: {
      marginTop: 12,
      borderRadius: radius.md,
      backgroundColor: palette.surfaceHover,
      paddingHorizontal: 14,
      paddingVertical: 10,
      fontFamily: font.nativeFamily.ui,
      fontSize: 13,
      color: color.status.error,
    },
    loading: {
      marginTop: 18,
      gap: 12,
    },
    quickAdd: {
      marginTop: 16,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      borderRadius: radius.pill,
      backgroundColor: palette.surfaceRaised,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    quickAddText: {
      flex: 1,
      fontFamily: font.nativeFamily.ui,
      fontSize: 13,
      color: palette.fgMuted,
    },
    pressed: {
      transform: [{ scale: 0.99 }],
    },
    section: {
      marginTop: 20,
    },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "baseline",
      justifyContent: "space-between",
      marginBottom: 8,
    },
    sectionTitle: {
      fontFamily: font.nativeFamily.display,
      fontSize: 18,
      fontWeight: "500",
      lineHeight: 22,
      color: palette.fg,
    },
    sectionMeta: {
      fontFamily: font.nativeFamily.ui,
      fontSize: 13,
      color: palette.fgMuted,
    },
    stack: {
      gap: 8,
    },
    documentRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      padding: 12,
    },
    documentBody: {
      flex: 1,
      minWidth: 0,
    },
    kindLabel: {
      marginBottom: 2,
      fontFamily: font.nativeFamily.ui,
      fontSize: 9,
      fontWeight: "500",
      letterSpacing: 0.36,
      color: palette.fgMuted,
    },
    documentTitle: {
      fontFamily: font.nativeFamily.ui,
      fontSize: 13,
      fontWeight: "500",
      lineHeight: 17,
      color: palette.fg,
    },
    documentSub: {
      marginTop: 2,
      fontFamily: font.nativeFamily.ui,
      fontSize: 11,
      lineHeight: 15,
      color: palette.fgMuted,
    },
    progressTrack: {
      marginTop: 8,
      height: 3,
      overflow: "hidden",
      borderRadius: radius.pill,
      backgroundColor: palette.border,
    },
    progressFill: {
      height: "100%",
      borderRadius: radius.pill,
    },
    emptyCard: {
      padding: 18,
    },
    emptyCardText: {
      fontFamily: font.nativeFamily.ui,
      fontSize: 13,
      lineHeight: 18,
      color: palette.fgSubtle,
    },
    recentGrid: {
      marginTop: 10,
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 14,
    },
    recentCard: {
      width: 104,
    },
    recentTextRow: {
      marginTop: 8,
      flexDirection: "row",
      alignItems: "flex-start",
    },
    recentText: {
      flex: 1,
      minWidth: 0,
    },
    recentTitle: {
      fontFamily: font.nativeFamily.ui,
      fontSize: 12,
      fontWeight: "500",
      lineHeight: 15,
      color: palette.fg,
    },
    recentSub: {
      marginTop: 2,
      fontFamily: font.nativeFamily.ui,
      fontSize: 11,
      color: palette.fgMuted,
    },
    dropWrap: {
      marginTop: 16,
    },
    dropZone: {
      minHeight: 360,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      borderWidth: 1.5,
      borderStyle: "dashed",
      borderColor: palette.borderStrong,
      borderRadius: 22,
      backgroundColor: palette.surfaceRaised,
      padding: 24,
    },
    faintCover: {
      position: "absolute",
      width: 58,
      height: 82,
      justifyContent: "flex-end",
      borderRadius: 4,
      backgroundColor: color.highlight.blue,
      opacity: 0.2,
      padding: 8,
    },
    faintCoverLeft: {
      left: 20,
      top: 32,
      transform: [{ rotate: "-9deg" }],
    },
    faintCoverRight: {
      right: 22,
      bottom: 42,
      transform: [{ rotate: "6deg" }],
    },
    faintCoverText: {
      fontFamily: font.nativeFamily.display,
      fontSize: 10,
      fontWeight: "500",
      lineHeight: 12,
      color: palette.fg,
    },
    dropIcon: {
      zIndex: 1,
      width: 48,
      height: 48,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: radius.pill,
      backgroundColor: palette.surface,
      shadowColor: palette.fg,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.08,
      shadowRadius: 16,
      elevation: 3,
    },
    dropTitle: {
      zIndex: 1,
      marginTop: 14,
      textAlign: "center",
      fontFamily: font.nativeFamily.display,
      fontSize: 18,
      fontWeight: "500",
      color: palette.fg,
    },
    dropLead: {
      zIndex: 1,
      marginTop: 4,
      textAlign: "center",
      fontFamily: font.nativeFamily.ui,
      fontSize: 12,
      lineHeight: 17,
      color: palette.fgSubtle,
    },
    linkImport: {
      zIndex: 1,
      marginTop: 14,
      width: "100%",
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      borderWidth: 1,
      borderColor: palette.borderStrong,
      borderRadius: radius.pill,
      backgroundColor: palette.surface,
      padding: 4,
    },
    linkPlaceholder: {
      flex: 1,
      paddingLeft: 12,
      fontFamily: font.nativeFamily.ui,
      fontSize: 11,
      color: palette.fgMuted,
    },
    linkButton: {
      height: 28,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: radius.pill,
      backgroundColor: palette.action,
      paddingHorizontal: 14,
    },
    linkButtonText: {
      fontFamily: font.nativeFamily.ui,
      fontSize: 11,
      fontWeight: "500",
      color: palette.actionFg,
    },
    dropHints: {
      marginTop: 14,
      gap: 8,
    },
    importHint: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    importHintText: {
      fontFamily: font.nativeFamily.ui,
      fontSize: 12,
      color: palette.fgSubtle,
    },
    filteredEmpty: {
      marginTop: 24,
      alignItems: "center",
      padding: 28,
    },
    filteredTitle: {
      marginTop: 12,
      fontFamily: font.nativeFamily.display,
      fontSize: 22,
      fontWeight: "500",
      color: palette.fg,
    },
    filteredBody: {
      marginTop: 4,
      fontFamily: font.nativeFamily.ui,
      fontSize: 13,
      color: palette.fgSubtle,
    },
    tabs: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      flexDirection: "row",
      justifyContent: "space-around",
      borderTopWidth: 1,
      borderTopColor: palette.border,
      backgroundColor: palette.bg,
      paddingTop: 12,
    },
    tabItem: {
      minWidth: 52,
      alignItems: "center",
      gap: 4,
    },
    primaryTab: {
      width: 36,
      height: 36,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: radius.pill,
      backgroundColor: palette.action,
    },
    tabLabel: {
      fontFamily: font.nativeFamily.ui,
      fontSize: 10,
      color: palette.fgMuted,
    },
    tabLabelActive: {
      color: palette.fg,
      fontWeight: "600",
    },
    toastWrap: {
      position: "absolute",
      left: 0,
      right: 0,
      alignItems: "center",
    },
    modalBackdrop: {
      flex: 1,
      justifyContent: "flex-end",
      backgroundColor: "rgba(20,15,10,0.35)",
    },
    modalSheet: {
      gap: 12,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      backgroundColor: palette.surface,
      padding: 20,
      paddingBottom: 40,
    },
    modalHeader: {
      marginBottom: 4,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    modalTitle: {
      fontFamily: font.nativeFamily.ui,
      fontSize: 17,
      fontWeight: "500",
      color: palette.fg,
    },
    modalBody: {
      fontFamily: font.nativeFamily.ui,
      fontSize: 15,
      lineHeight: 22,
      color: palette.fgSubtle,
    },
    modalStrong: {
      fontWeight: "600",
    },
    modalFooter: {
      marginTop: 12,
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 8,
    },
  });

export type DashboardStyles = ReturnType<typeof buildDashboardStyles>;
